name: Build Docker

on:
  workflow_dispatch:
    inputs:
      CLASH_VERSION:
        description: 'clash version'
        type: environment
        required: true
      DEVICE_PLATFORM:
        description: 'device paltform'
        type: environment
        required: true

jobs:

  Docker-Images:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: build_environment
    env:
      CLASH_VERSION: ${{ vars.CLASH_VERSION }}
      DEVICE_PLATFORM: ${{ vars.DEVICE_PLATFORM }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login To Alibaba Cloud Container Registry
        run: |
          docker login -u ${{ secrets.ALIYUN_USERNAME }} -p '${{ secrets.ALIYUN_PASSWD }}' registry.cn-hangzhou.aliyuncs.com

      - name: Build & Push Normal Image (Default)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            CLASH_VERSION=${{ env.CLASH_VERSION }}
            DEVICE_PLATFORM=${{ env.DEVICE_PLATFORM }}
          file: Dockerfile
          context: .
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/clash:${{ env.DEVICE_PLATFORM }}-${{ env.CLASH_VERSION }}

